# Generated by Django 3.0 on 2021-02-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_artifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='category',
            field=models.CharField(choices=[('1', 'Armor'), ('2', 'Potion'), ('3', 'Ring'), ('4', 'Rod'), ('5', 'Scroll'), ('6', 'Staff'), ('7', 'Wand'), ('8', 'Weapon'), ('9', 'Wondrous Item')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artifact',
            name='rarity',
            field=models.CharField(choices=[('1', 'Common'), ('2', 'Uncommon'), ('3', 'Rare'), ('4', 'Very Rare'), ('5', 'Legendary'), ('6', 'Artifact'), ('7', 'Unknown Rarity')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
