# Generated by Django 3.0 on 2021-02-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210218_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='attunement',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
