# Generated by Django 3.0 on 2021-02-18 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_artifact_attunement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mango',
        ),
    ]
